### ISSUE TITLE
Wrong link for local net

### ISSUE THREAD

**Issue by ilyar** [broxus/ton-wallet-crystal-browser-extension#3]
![image](https://user-images.githubusercontent.com/761285/159969235-90691802-03a0-4319-8c29-0137addbb25a.png)

![image](https://user-images.githubusercontent.com/761285/159969325-f30fcc13-a14e-4ea4-8b13-1028b037af27.png)

**Got:** 
`https://127.0.0.1/messages/messageDetails?id=586385f9a957e2d5ca234143e8aa3c1b5aa2efedfc1f61cfc15a458876548e2b`

**Expect:**
`http://localhost/transactions/transactionDetails?id=586385f9a957e2d5ca234143e8aa3c1b5aa2efedfc1f61cfc15a458876548e2b`

**Comment by Rexagon** [comment]
Thanks! It will be fixed in the next release

**Comment by ilyar** [comment]
@Rexagon https://github.com/broxus/ever-wallet-browser-extension/commit/f995cd4d5fc2a9135d4bfb9e0fb7eaa6041433ae#r70332117

**Comment by Rexagon** [comment]
Fixed in [`ee93047`](https://github.com/broxus/ever-wallet-browser-extension/commit/ee93047e0cf3b5c0fd599ef0961e36db4e5fa922)
